# Generated by Django 2.0.2 on 2019-12-11 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='account',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('account_no', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('no_books_issued', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('subtitle', models.CharField(max_length=250)),
                ('author', models.CharField(max_length=100)),
                ('isbn', models.CharField(max_length=13)),
                ('accounts', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='books.account')),
            ],
        ),
    ]
