# Generated by Django 2.0.2 on 2019-12-11 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='accounts',
        ),
        migrations.DeleteModel(
            name='account',
        ),
    ]
