# Generated by Django 2.0.2 on 2019-12-13 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20191212_0233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='id',
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=250, primary_key=True, serialize=False),
        ),
    ]
