# Generated by Django 2.0.2 on 2019-12-13 02:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20191213_0810'),
    ]

    operations = [
        migrations.CreateModel(
            name='account',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('account_no', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('no_books_issued', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='issued_by',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.account')),
                ('Book_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.Book')),
            ],
        ),
    ]
